source_server       = "banking-int-snapshot.cluster-cb5ytt5zm3va.eu-central-1.rds.amazonaws.com"
source_cluster_name = "thedock-dms"
target_db_username  = "thedock"
source_db_username  = "thedock"
target_db_password  = "Password123!"
source_db_password  = "Password123!"
database_name       = "partner-ehotel"
environment         = "plgrnd-j-a"
default_subnet_group= "dmssubnet"
private_key_path = "~\\.ssh\\id_rsa_oci"
target_availability_zone = "eu-central-1b"
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK1fkb0aEeB3+UfALnb5mLsj9WEpMoxDR5xg717KbK3XpzYye9Z8CqTT1Btp6kVoJ5l+YE9l7v7ExoiEcp2uVYHn15WDVBYycUrw6yIg46hGbyUcveZ+AVHWdY+Zln3aUc/Bn6IFYG5UoMOGAnYJZhYntrhEjLVuc5pi5a9a8tir24fZt+ng8n3MxTUn8NPt9b34LukeNWOIgqsLQlButLFODWKrXbx4o6iQU7/9tWl3oVrU+bVb5L5KMlbP++rb4Vy0MKOGLKooLFwq9u9WeYH29Gq/8bICoRBvpPXzjKPCtuFB0c6TrPLOZLwMpfOkJieFww2fhs+f+i5q+wmtP1JCfAfKeH3bdewlxszN2m95OzA8VZlryfkedFTKcyxfqdAngz1Hf6mxIU32rsRmXVGqQssH81TBO7DUHMnyNTuZ0uKPSyH3+4EtWzZ2dp/1OuAOBdKdGsvBYZkbj73C5ohhZaVy9p3yDUCSFM8V8Mqg9zcwfcTC4S/xLLY+haHFk= andonoovj@JumpySkyBison"
